source 'https://rubygems.org'

gem 'rails', '3.2.0'

gem 'crichton', path: '/Users/svalentine/Projects/temp/crichton'#git: 'git@github.com:mdsol/crichton.git', branch: 'develop'
gem 'launchy'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'rack', '=1.4.1' # To silence deprecation warnings.

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'nokogiri'

# gem 'ffi-rzmq',  '~> 2.0.1' Uncomment to use zeromq
gem 'yajl-ruby', '~> 1.2.0'
gem 'faraday',   '~> 0.9.0'

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
end